import { ALL_EXAMPLE_TERMS } from './allTranslations'

export const EXAMPLE_TERMS = {
  EN: {
    "Master's Thesis": "/examples/business-model.pdf",
    "Bachelor's Thesis": "/examples/business-model.pdf",
    "Dissertation": "/examples/business-model.pdf",
    "Habilitation": "/examples/business-model.pdf",
    "Research Proposal": "/examples/business-model.pdf",
    "Paper": "/examples/business-model.pdf",
    "Essay": "/examples/business-model.pdf",
    "Manuscript": "/examples/business-model.pdf",
    "Whitepaper": "/examples/business-model.pdf",
    "Literature Review": "/examples/business-model.pdf",
    "Exposé": "/examples/business-model.pdf",
    "Website": "/examples/business-model.pdf",
    "Landing Page": "/examples/business-model.pdf",
    "SaaS": "/examples/business-model.pdf",
    "UX Flow": "/examples/business-model.pdf",
    "User Journey": "/examples/business-model.pdf",
    "Navigation System": "/examples/business-model.pdf",
    "Information Architecture": "/examples/business-model.pdf",
    "Content Structure": "/examples/business-model.pdf",
    "Conversion Flow": "/examples/business-model.pdf",
    "Product Page": "/examples/business-model.pdf",
    "Prompt": "/examples/business-model.pdf",
    "Prompt System": "/examples/business-model.pdf",
    "Prompt Chain": "/examples/business-model.pdf",
    "Agent Architecture": "/examples/business-model.pdf",
    "Tool Workflow": "/examples/business-model.pdf",
    "LLM Workflow": "/examples/business-model.pdf",
    "System Prompt": "/examples/business-model.pdf",
    "Automation Logic": "/examples/business-model.pdf",
    "Codebase": "/examples/business-model.pdf",
    "API Design": "/examples/business-model.pdf",
    "Backend Flow": "/examples/business-model.pdf",
    "Data Model": "/examples/business-model.pdf",
    "State Machine": "/examples/business-model.pdf",
    "Architecture": "/examples/business-model.pdf",
    "Repository Structure": "/examples/business-model.pdf",
    "Software System": "/examples/business-model.pdf",
    "Brand Identity": "/examples/business-model.pdf",
    "Naming": "/examples/business-model.pdf",
    "Claim": "/examples/business-model.pdf",
    "Positioning": "/examples/business-model.pdf",
    "Narrative Structure": "/examples/business-model.pdf",
    "Messaging System": "/examples/business-model.pdf",
    "Communication Strategy": "/examples/business-model.pdf",
    "Storyline": "/examples/business-model.pdf",
    "Business Model": "/examples/business-model.pdf",
    "Offer Architecture": "/examples/business-model.pdf",
    "Decision Tree": "/examples/business-model.pdf",
    "Rule System": "/examples/business-model.pdf",
    "Organization Structure": "/examples/business-model.pdf",
    "Process Logic": "/examples/business-model.pdf",
    "Product Strategy": "/examples/business-model.pdf",
    "Overall Strategy": "/examples/business-model.pdf"
  },
  DE: {
    "Masterarbeit": "/examples/business-model.pdf",
    "Bachelorarbeit": "/examples/business-model.pdf",
    "Dissertation": "/examples/business-model.pdf",
    "Habilitation": "/examples/business-model.pdf",
    "Forschungsantrag": "/examples/business-model.pdf",
    "Paper": "/examples/business-model.pdf",
    "Essay": "/examples/business-model.pdf",
    "Manuskript": "/examples/business-model.pdf",
    "Whitepaper": "/examples/business-model.pdf",
    "Literaturreview": "/examples/business-model.pdf",
    "Exposé": "/examples/business-model.pdf",
    "Webseite": "/examples/business-model.pdf",
    "Landingpage": "/examples/business-model.pdf",
    "SaaS": "/examples/business-model.pdf",
    "UX-Flow": "/examples/business-model.pdf",
    "User Journey": "/examples/business-model.pdf",
    "Navigationssystem": "/examples/business-model.pdf",
    "Informationsarchitektur": "/examples/business-model.pdf",
    "Content-Struktur": "/examples/business-model.pdf",
    "Conversion-Flow": "/examples/business-model.pdf",
    "Produktseite": "/examples/business-model.pdf",
    "Prompt": "/examples/business-model.pdf",
    "Prompt-System": "/examples/business-model.pdf",
    "Prompt Chain": "/examples/business-model.pdf",
    "Agent-Architektur": "/examples/business-model.pdf",
    "Tool-Workflow": "/examples/business-model.pdf",
    "LLM-Workflow": "/examples/business-model.pdf",
    "System-Prompt": "/examples/business-model.pdf",
    "Automations-Logik": "/examples/business-model.pdf",
    "Codebasis": "/examples/business-model.pdf",
    "API-Design": "/examples/business-model.pdf",
    "Backend-Flow": "/examples/business-model.pdf",
    "Datenmodell": "/examples/business-model.pdf",
    "State Machine": "/examples/business-model.pdf",
    "Architektur": "/examples/business-model.pdf",
    "Repository-Struktur": "/examples/business-model.pdf",
    "Software-System": "/examples/business-model.pdf",
    "Markenidentität": "/examples/business-model.pdf",
    "Naming": "/examples/business-model.pdf",
    "Claim": "/examples/business-model.pdf",
    "Positionierung": "/examples/business-model.pdf",
    "Narrative Struktur": "/examples/business-model.pdf",
    "Messaging-System": "/examples/business-model.pdf",
    "Kommunikationsstrategie": "/examples/business-model.pdf",
    "Storyline": "/examples/business-model.pdf",
    "Geschäftsmodell": "/examples/business-model.pdf",
    "Angebotsarchitektur": "/examples/business-model.pdf",
    "Entscheidungsbaum": "/examples/business-model.pdf",
    "Regelwerk": "/examples/business-model.pdf",
    "Organisationsstruktur": "/examples/business-model.pdf",
    "Prozesslogik": "/examples/business-model.pdf",
    "Produktstrategie": "/examples/business-model.pdf",
    "Gesamtstrategie": "/examples/business-model.pdf"
  },
  ES: {
    "Tesis de Maestría": "/examples/business-model.pdf",
    "Tesis de Licenciatura": "/examples/business-model.pdf",
    "Disertación": "/examples/business-model.pdf",
    "Habilitación": "/examples/business-model.pdf",
    "Propuesta de Investigación": "/examples/business-model.pdf",
    "Artículo": "/examples/business-model.pdf",
    "Ensayo": "/examples/business-model.pdf",
    "Manuscrito": "/examples/business-model.pdf",
    "Libro Blanco": "/examples/business-model.pdf",
    "Revisión Bibliográfica": "/examples/business-model.pdf",
    "Exposición": "/examples/business-model.pdf",
    "Sitio Web": "/examples/business-model.pdf",
    "Página de Aterrizaje": "/examples/business-model.pdf",
    "SaaS": "/examples/business-model.pdf",
    "Flujo UX": "/examples/business-model.pdf",
    "Viaje del Usuario": "/examples/business-model.pdf",
    "Sistema de Navegación": "/examples/business-model.pdf",
    "Arquitectura de Información": "/examples/business-model.pdf",
    "Estructura de Contenido": "/examples/business-model.pdf",
    "Flujo de Conversión": "/examples/business-model.pdf",
    "Página de Producto": "/examples/business-model.pdf",
    "Prompt": "/examples/business-model.pdf",
    "Sistema de Prompts": "/examples/business-model.pdf",
    "Cadena de Prompts": "/examples/business-model.pdf",
    "Arquitectura de Agentes": "/examples/business-model.pdf",
    "Flujo de Herramientas": "/examples/business-model.pdf",
    "Flujo LLM": "/examples/business-model.pdf",
    "Prompt del Sistema": "/examples/business-model.pdf",
    "Lógica de Automatización": "/examples/business-model.pdf",
    "Base de Código": "/examples/business-model.pdf",
    "Diseño de API": "/examples/business-model.pdf",
    "Flujo Backend": "/examples/business-model.pdf",
    "Modelo de Datos": "/examples/business-model.pdf",
    "Máquina de Estados": "/examples/business-model.pdf",
    "Arquitectura": "/examples/business-model.pdf",
    "Estructura de Repositorio": "/examples/business-model.pdf",
    "Sistema de Software": "/examples/business-model.pdf",
    "Identidad de Marca": "/examples/business-model.pdf",
    "Naming": "/examples/business-model.pdf",
    "Claim": "/examples/business-model.pdf",
    "Posicionamiento": "/examples/business-model.pdf",
    "Estructura Narrativa": "/examples/business-model.pdf",
    "Sistema de Mensajería": "/examples/business-model.pdf",
    "Estrategia de Comunicación": "/examples/business-model.pdf",
    "Historia": "/examples/business-model.pdf",
    "Modelo de Negocio": "/examples/business-model.pdf",
    "Arquitectura de Oferta": "/examples/business-model.pdf",
    "Árbol de Decisiones": "/examples/business-model.pdf",
    "Sistema de Reglas": "/examples/business-model.pdf",
    "Estructura Organizacional": "/examples/business-model.pdf",
    "Lógica de Procesos": "/examples/business-model.pdf",
    "Estrategia de Producto": "/examples/business-model.pdf",
    "Estrategia General": "/examples/business-model.pdf"
  },
  ...ALL_EXAMPLE_TERMS
} as const

export type LanguageCode = keyof typeof EXAMPLE_TERMS

export function isExampleTerm(text: string, lang: LanguageCode): boolean {
  const terms = EXAMPLE_TERMS[lang] || EXAMPLE_TERMS['EN']
  return text in terms
}

export function getExamplePDF(text: string, lang: LanguageCode): string | null {
  const terms = EXAMPLE_TERMS[lang] || EXAMPLE_TERMS['EN']
  return terms[text as keyof typeof terms] || null
}
